### ISSUE TITLE
Action items from first meeting

### ISSUE THREAD

**Issue by garthtarr** [IBS-AR/IBS-AR.github.io#2]
- [x] Sam to send the email addresses to Peter (which is done now I see)
- [x] Garth to follow up about color/brand/style guide with IBS
- [x] Sam to move past conference sites as standalone sites in a repo
- [ ] Emi, Peter, Sam and Garth to populate the pages as per the table in minutes

Pages

- [x] Home, Peter
- [x] About, Peter
- [x] Council, Garth. We should include past council members and move to have a [database](https://github.com/IBS-AR/IBS-AR.github.io/tree/main/data) – someone needs to work with Warren to dig up the historical records. _Garth has extracted records back to 2007... to go further back we will need to find alternative historical records._
- [x] News, Garth. Include the bulletin here?
- [x] Prizes and Awards, Garth. Rename header simply as "Award"?
- [x] Conferences, Emi. Link to old conferences with some attendance summaries if possible
- [ ] #3
- [x] Contact, Peter/Sam. We should have a society email if we don’t have one?
- [x] Past conference complete site, Sam

**Comment by emitanaka** [comment]
I think this all done so closing this issue
